### ISSUE TITLE
Incorrect Listing Details

### ISSUE THREAD

**Issue by loc8malta** [loc8malta/Home#9]
From ‘Sunshine Boutique’ downward (bottom 3 from the left) seems like when tapping on them they’re referring to a listing which isn’t even showing up on iOS - A different Just Burger. It’s not going to the details of the selected listings on the bottom 3. I’m not sure whether it’s only happening on the Samsung or on quite a few devices. Check it out and let me know what your feedback is! :)

**Comment by rodneygreenpops** [comment]
Daniel, important is to note that the "Just Burger" Listing that is showing is not the same one that is live on system. It looks like this is the one Clint had initially created. This shouldn't be available since we had purged all data at one point

**Comment by gaucidaniel** [comment]
Since the listings are sorted by location, I can't really tell which listings are at the bottom. Would you mind giving me their names? I tested this on all listings however the correct one always shows up.

With regards to the Just Burger listing, that's just data that I have hardcoded in the app. What I'm assuming is happening is that for some reason the listing data is not loading and as such not replacing the hardcoded data.

**Comment by gaucidaniel** [comment]
Added a message if the listing failed to load. This should help up find out the issue.
